services:
  dev:
    image: ghcr.io/flipstone/haskell-tools:debian-stable-ghc-9.6.5-2024-05-15-5314c42
    volumes:
      - .:${PROJECT_DIR}
      - flipstone_stack_root:/stack-root
    working_dir: ${PROJECT_DIR}
    environment:
      STACK_ROOT: /stack-root
      IN_DEV_CONTAINER: "true"
      # Pass through the CI variable from GitHub (or set it to `true` locally
      # for debugging CI builds)
      CI:

volumes:
  flipstone_stack_root:
    external: true
