name: beeline
version: 0.1.0.0
license: MIT
author: "Flipstone Technology Partners"
maintainer: "development@flipstone.com"
git: "git@github.com:flipstone/beeline.git"

extra-source-files:
  - README.md

library:
  source-dirs: src
  exposed-modules:
    - Beeline
    - Beeline.RouteDocumenter
    - Beeline.RouteGenerator
    - Beeline.Router
    - Beeline.RouteRecognizer

dependencies:
  - base
  - http-types
  - shrubbery
  - text

ghc-options:
  - -Wall
  - -Wno-name-shadowing

tests:
  spec:
    source-dirs: test
    main: Main.hs
    dependencies:
      - base
      - beeline
      - hedgehog
    ghc-options:
      - -j
      - -Wall
      - -Werror
      - -Wcompat
      - -Widentities
      - -Wincomplete-uni-patterns
      - -Wincomplete-record-updates
      - -Wmissing-local-signatures
      - -Wmissing-export-lists
      - -Wno-implicit-prelude
      - -Wno-safe
      - -Wno-unsafe
      - -Wnoncanonical-monad-instances
      - -Wredundant-constraints
      - -Wpartial-fields
      - -Wmissed-specialisations
      - -Woverflowed-literals
