resolver: lts-22.39
allow-different-user: true
system-ghc: true
install-ghc: false
packages:
  - beeline-routing
  - beeline-http-client
  - beeline-examples

flags:
  beeline-routing:
    strict: true
  beeline-http-client:
    strict: true
  beeline-examples:
    strict: true

extra-deps:
  - github: flipstone/shrubbery
    commit: ae5c282af3029179d5ab43a927aecbc8e44971e4
