resolver: lts-22.39
allow-different-user: true
system-ghc: true
install-ghc: false
packages:
  - beeline-routing
  - beeline-http-client
  - beeline-examples

flags:
  beeline-routing:
    strict: true
  beeline-http-client:
    strict: true
  beeline-examples:
    strict: true

extra-deps:
  - github: flipstone/shrubbery
    commit: 95c5bf28d03ed8b4df163a98b878fa515bf40604
