resolver: lts-22.39
allow-different-user: true
system-ghc: true
install-ghc: false
packages:
  - beeline-params
  - beeline-routing
  - beeline-http-client
  - beeline-examples

flags:
  beeline-params:
    ci: true
  beeline-routing:
    ci: true
  beeline-http-client:
    ci: true
  beeline-examples:
    ci: true

extra-deps:
  - github: flipstone/shrubbery
    commit: a064ede07e01b753a6eb310fc24d9fd8da1ad826
  - git: https://github.com/flipstone/henforcer.git
    commit: f3c2b1e461a37e7ff88d795379edd7386bfa8557
  - pollock-0.1.0.3
  - tomland-1.3.3.3
  - validation-selective-0.2.0.0
