resolver: lts-20.11
allow-different-user: true
system-ghc: true
packages:
  - beeline-routing
  - beeline-http-client
  - beeline-examples

flags:
  beeline-routing:
    strict: true
  beeline-http-client:
    strict: true
  beeline-examples:
    strict: true

extra-deps:
  - git: https://github.com/flipstone/shrubbery.git
    commit: ba602d04c5f85a0909fa4efa2227c07178bdb513
