name:                beeline-http-client
version:             0.9.0.1
github:              "flipstone/beeline/beeline-http-client"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/json-fleece-http#readme>
tested-with:
    GHC == 8.10.7, GHC == 9.0.2, GHC == 9.2.8, GHC == 9.4.8, GHC == 9.6.6, GHC == 9.8.4, GHC == 9.10.1
flags:
  ci:
    description: More strict ghc options used for development and ci, not intended for end-use.
    manual: true
    default: false

when:
  - condition: flag(ci)
    ghc-options:
        - -O2
        - -Wall
        - -Werror
        - -Wcompat
        - -Widentities
        - -Wmissed-specialisations
        - -Wmissing-local-signatures
        - -Wmissing-export-lists
        - -Wpartial-fields
        - -Wunused-packages
    when:
        - condition: impl (ghc >= 9.0)
          ghc-options:
            - -Winvalid-haddock
        - condition: impl (ghc >= 9.2)
          ghc-options:
            - -Wimplicit-lift
            - -Woperator-whitespace
            - -Wredundant-bang-patterns
        - condition: impl (ghc >= 9.4)
          ghc-options:
            - -Wredundant-strictness-flags
        - condition: impl (ghc >= 9.6)
          dependencies:
            - henforcer
          ghc-options:
            - -fplugin Henforcer
        - condition: impl (ghc >= 9.8)
          ghc-options:
            - -Wincomplete-export-warnings
            - -Wmissing-poly-kind-signatures
            - -Wterm-variable-capture
        - condition: impl (ghc >= 9.10)
          ghc-options:
            - -Wdefaulted-exception-context

library:
  source-dirs: src
  exposed-modules:
    - Beeline.HTTP.Client
    - Beeline.HTTP.Client.Body
    - Beeline.HTTP.Client.ContentType
    - Beeline.HTTP.Client.Operation
  dependencies:
    - base >= 4.7 && < 5
    - beeline-params >= 0.1 && < 0.2
    - beeline-routing >= 0.3 && < 0.4
    - bytestring >= 0.10 && < 0.13
    - containers >= 0.6 && < 0.9
    - http-client >= 0.6 && < 0.8
    - http-types >= 0.12 && < 0.13
    - network-uri >= 2.6 && < 2.7
    - text >= 1.2 && < 2.2

tests:
  beeline-http-client-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    when:
      - condition: flag(ci)
        ghc-options:
          - -j

    dependencies:
      - base >= 4.7 && < 5
      - beeline-http-client
      - beeline-params >= 0.1 && < 0.2
      - beeline-routing >= 0.3 && < 0.4
      - bytestring >= 0.10 && < 0.13
      - hedgehog
      - http-client >= 0.6 && < 0.8
      - http-types >= 0.12 && < 0.13
      - random >= 1.2 &&  < 1.4
      - text >= 1.2 && < 2.2
      - wai >= 3.2 && < 3.3
      - warp >= 3.3 && < 3.5
