name: beeline-params
version: 0.1.0.0
license: MIT
author: "Flipstone Technology Partners"
maintainer: "development@flipstone.com"
github: "flipstone/beeline/beeline-params"


description:         Please see the README on GitHub at <https://github.com/flipstone/beeline#readme>
tested-with:
    GHC == 8.10.7, GHC == 9.0.2, GHC == 9.2.8, GHC == 9.4.8, GHC == 9.6.6, GHC == 9.8.4, GHC == 9.10.1

flags:
  ci:
    description: More strict ghc options used for development and ci, not intended for end-use.
    manual: true
    default: false

when:
  - condition: flag(ci)
    ghc-options:
        - -O2
        - -Wall
        - -Werror
        - -Wcompat
        - -fwrite-ide-info
        - -hiedir=.hie
        - -Widentities
        - -Wmissed-specialisations
        - -Wmissing-local-signatures
        - -Wmissing-export-lists
        - -Wpartial-fields
        - -Wunused-packages
    when:
        - condition: impl (ghc >= 9.0)
          ghc-options:
            - -Winvalid-haddock
        - condition: impl (ghc >= 9.2)
          ghc-options:
            - -Wimplicit-lift
            - -Woperator-whitespace
            - -Wredundant-bang-patterns
        - condition: impl (ghc >= 9.4)
          ghc-options:
            - -Wredundant-strictness-flags
        - condition: impl (ghc >= 9.6)
          dependencies:
            - henforcer
          ghc-options:
            - -fplugin Henforcer
        - condition: impl (ghc >= 9.8)
          ghc-options:
            - -Wincomplete-export-warnings
            - -Wmissing-poly-kind-signatures
            - -Wterm-variable-capture
        - condition: impl (ghc >= 9.10)
          ghc-options:
            - -Wdefaulted-exception-context

library:
  source-dirs: src
  exposed-modules:
    - Beeline.Params
    - Beeline.Params.CookieSchema
    - Beeline.Params.HeaderSchema
    - Beeline.Params.ParameterDefinition
    - Beeline.Params.ParameterSchema
    - Beeline.Params.QuerySchema
  dependencies:
    - attoparsec >= 0.13 && < 0.15
    - base >= 4.7 && < 5
    - bytestring >= 0.10 && < 0.13
    - case-insensitive >= 1.2 && < 1.3
    - containers >= 0.6 && < 0.9
    - cookie >= 0.4 && < 0.5
    - dlist >= 1.0 && < 1.1
    - http-types >= 0.12 && < 0.13
    - scientific >= 0.3 && < 0.4
    - text >= 1.2 && < 2.2

tests:
  beeline-params-test:
    source-dirs: test
    main: Main.hs
    dependencies:
      - base
      - beeline-params
      - bytestring
      - hedgehog
      - http-types
      - cookie
      - scientific >= 0.3 && < 0.4
      - text
    when:
      - condition: flag(ci)
        ghc-options:
          - -j
