name: beeline-routing
version: 0.2.4.1
license: MIT
author: "Flipstone Technology Partners"
maintainer: "development@flipstone.com"
github: "flipstone/beeline/beeline-routing"

flags:
  strict:
    description: More strict ghc options used for development and ci, not intended for end-use.
    manual: true
    default: false

when:
  - condition: flag(strict)
    then:
      ghc-options:
        - -Weverything
        - -Werror
        - -Wno-missing-local-signatures
        - -Wno-monomorphism-restriction
        - -Wno-missing-kind-signatures
        - -Wno-prepositive-qualified-module
        - -Wno-implicit-prelude
        - -Wno-safe
        - -Wno-unsafe
        - -Wno-missing-safe-haskell-mode
        - -Wno-missing-deriving-strategies
        - -Wno-all-missed-specialisations
        - -Wno-missed-specialisations
        - -Wno-unticked-promoted-constructors
    else:
      ghc-options:
        - -Wall

  - condition: flag(strict) && impl(ghc >= 9.8.1)
    ghc-options:
      - -Wno-missing-role-annotations
      - -Wno-term-variable-capture

dependencies:
  - base
  - http-types
  - shrubbery >= 0.1 && < 0.3
  - text
  - scientific >= 0.3 && < 0.4

library:
  source-dirs: src
  exposed-modules:
    - Beeline.Routing
    - Beeline.Routing.ParameterDefinition
    - Beeline.Routing.RouteDocumenter
    - Beeline.Routing.RouteGenerator
    - Beeline.Routing.Router
    - Beeline.Routing.RouteRecognizer
  dependencies:
    - attoparsec
    - dlist
    - containers >= 0.6 && < 0.8

tests:
  spec:
    source-dirs: test
    main: Main.hs
    dependencies:
      - base
      - beeline-routing
      - hedgehog
    ghc-options:
      - -j
